### ISSUE TITLE
Gojira fins only actuate correctly if attached to nosecone nodes

### ISSUE THREAD

**Issue by Kari1407** [damonvv/TundraExploration#46]
So I've seen some people (and me) complaining about the rear fins actuating only 1-2 degrees instead of the intended. This is what happens

The issue:

All gojira fins don't actuate properly UNLESS they are attached to the nosecone nodes (edit: to be clear, the nodes you use to attach the front fins). All 3 nosecones were tested to verify this and I tried attaching the fins to different parts, such as stock parts, but I didn't record it.

How to reproduce:

Attach any mk4 gojira fins to the nosecone nodes, activave pitch yaw roll and try to actuate them using WASD. Do the same thing attaching them to any other node in any part and see the differences.

Evidence:

https://www.youtube.com/watch?v=CvZal_6vvps (by me)

https://www.youtube.com/watch?v=jEKkD2l6XaY  (by Aria. It's a little hard to see but it's there too)

I tested this on 1.11.2 clean KSP install with no DLC's, only Tundra via CKAN. I cannot verify anything about Aria's install.

[KSP.log](https://github.com/damonvv/TundraExploration/files/6328501/KSP.log) if needed

**Comment by JadeOfMaar** [comment]
Sorry, Kari. The stock elevon module was not designed for Starship-like controls in mind, neither has it been updated since Starship became super popular, and no plugin modder has been contacted to try to code a proper module. Currently, the only option for steering is to button-mash to deploy or un-deploy the fins.
Elevons (not only Starship's fins, but any and all. Go ahead and try stock ones) do not like being attached with rotation like Starship's own. This is why WASD response is off by default.
