### ISSUE TITLE
The engines have late response and the Starship is unplayable

### ISSUE THREAD

**Issue by XRazorBlade** [damonvv/TundraExploration#65]
The first bug is that all the engines in Tundra Exploration Pack have a late response when I throttle up the engines, and it makes things complicated when I try to land the Falcon 9, the Superheavy or the Starship. I don't know if this is a bug or a feature to add realistic physics to the engines, but it would be more simple if you can fix this, please. The second bug is the most annoying and it makes the Starship unplayable. If I try to launch the Starhip (the Superheavy + the ship stacked), after a few seconds it starts wobbling like hell and I'm not able to control it anymore, so it makes the Starship useless and unplayable, and I've tried to add struts or different decouplers, but it's the same result. All of these things happened since the recent update, so please try and fix these bugs, because I've used this mod for a long time and did a lot of missions with the Starship and Falcon 9, and now I can't use the mod anymore, because of these bugs.

**Comment by SofieBrink** [comment]
The first thing you mentioned is a feature, the engines are supposed to take around 2 seconds to come up to full throttle. Installing mechjeb removes this feature.
If the engine takes more then two seconds to start up, let me know because i’ve seen that bug before and i’ll look for the fix.
The second is incredibly unlikely to be fixed as Damon has lost his motivation to work on starship.
I recommend you download SEP by Kari for all starship related stuff
https://github.com/Kari1407/Starship-Expansion-Project

**Comment by xTr3mee** [comment]
try autostrut that may work
